### ISSUE TITLE
Feature: User can search for a stock by its ticker symbol

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a stock by its ticker symbol in the search bar which will show a description of the stock.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="111" alt="Screen Shot 2021-06-08 at 11 54 32 AM" src="https://user-images.githubusercontent.com/82472092/121241444-4d045300-c850-11eb-9773-3089cd962e27.png">
<img width="435" alt="Screen Shot 2021-06-08 at 11 54 55 AM" src="https://user-images.githubusercontent.com/82472092/121241479-58f01500-c850-11eb-913e-103e0ce4455b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a div for the header
- [x] Inside the created div, include a 'Browse', 'Trending Stocks' and 'Watchlist' button
- [x] Also inside the div, create a form
- [x] For the form, create a text input with the placeholder 'Search Companies...'
- [x] Add the magnifying glass icon into the input form
- [x] Style all elements in the header
- [x] Make sure that the inputs from the form is being stored properly
- [x] Test that the data from the form can be used with the API request
- [x] Make sure the app looks good on both desktop and mobile
- [x] Remove all unnecessary styling
- [x] Test functionality  
- [x] Fix all errors
