### ISSUE TITLE
Feature: User can add a stock to their watchlist

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a stock to their watchlist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="218" alt="Screen Shot 2021-06-08 at 6 32 45 PM" src="https://user-images.githubusercontent.com/82472092/121278680-fa468d80-c887-11eb-8e84-10fc0c1494e1.png">
<img width="434" alt="Screen Shot 2021-06-08 at 6 32 57 PM" src="https://user-images.githubusercontent.com/82472092/121278688-fc105100-c887-11eb-80e0-784196e04bdc.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the submit event handler, create an entry for the stock that the user searched for
- [x] The entry should include the stock's full company name, ticker symbol, current market price, today's percentage, today's low, today's high, and the description of the company. 
- [x] Add an icon to the bottom right corner of the entry
- [x] Style the stock entry.
- [x] Add an event listener on that icon for the 'click' event.
- [x] In the event listener, store the data of the searched stock into the data model.
- [x] Create a dom tree for the watchlist section. 
- [x] In the watchlist section, add the entry for the searched stock that was added earlier.
- [x] The entry in the watchlist section should include the stock ticker symbol, current price, today's low and today's high.
- [x] The watchlist anchor tag should change the view of the website so that the entries are shown. 
- [x] Style the watchlist entries.
- [x] Make sure that the data is saved in the local storage.
- [x] Make sure that the page reloads where the user left off.
- [x] Make sure that the website looks good both on desktop and mobile.
- [x] Remove all unnecessary styling. 
- [x] Test all functionality. 
- [x] Fix all errors.
