### ISSUE TITLE
Feature: User can delete a stock from their watchlist

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a stock from their watchlist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="438" alt="Screen Shot 2021-06-10 at 11 32 37 AM" src="https://user-images.githubusercontent.com/82472092/121579202-5d4b3800-c9e0-11eb-8555-65fe58cb1a78.png">
<img width="108" alt="Screen Shot 2021-06-10 at 11 32 30 AM" src="https://user-images.githubusercontent.com/82472092/121579217-60462880-c9e0-11eb-8cd0-b571afc3afcb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make each entry in the watchlist clickable
- [x] When the entry is clicked, change the view to the 'search' view
- [x] Create a new result like the search result but with the data of the clicked on stock
- [x] Add a delete button
- [x] Add an event listener for the delete button
- [x] When the delete button is clicked, store that entry's data into the data model
- [x] Pop up a modal for confirmation
- [x] If the cancel button is clicked, change to the 'search' view
- [x] If the confirm button is clicked, change to the 'watchlist' view
- [x] Remove that entry from the watchlist both on the document and also in the data model
- [x] Remove all unnecessary styling
- [x] Test all functionality
- [x] Fix all errors
