### ISSUE TITLE
Feature: User can view trending stocks

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view trending stocks

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="436" alt="Screen Shot 2021-06-10 at 4 30 24 PM" src="https://user-images.githubusercontent.com/82472092/121609673-37865900-ca09-11eb-8dd0-feeb41c3ba43.png">
<img width="110" alt="Screen Shot 2021-06-10 at 4 30 34 PM" src="https://user-images.githubusercontent.com/82472092/121609675-39501c80-ca09-11eb-8fc5-61168d635b16.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a div after the watchlist to put trending stocks
- [x] Inside that div, create a header and a container that holds all the trending stocks
- [x] Style the trending stocks section
- [x] Create a function that will take the data from the api and create a DOM tree
- [x] Append each trending stock to the container
- [x] Style the container for each trending stock
- [x] Add an event listener to the trending stock nav bar button to change the view to show only the trending stocks section
- [x] Remove all unnecessary styling
- [x] Test all functionality 
- [x] Fix all errors
