### ISSUE TITLE
Feature: User can add a trending stock to their watchlist

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a trending stock to their watchlist

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="111" alt="Screen Shot 2021-06-11 at 12 59 57 PM" src="https://user-images.githubusercontent.com/82472092/121742649-f9467380-cab4-11eb-975f-e786762a59e2.png">
<img width="431" alt="Screen Shot 2021-06-11 at 1 00 05 PM" src="https://user-images.githubusercontent.com/82472092/121742654-f9df0a00-cab4-11eb-956d-55660cd4953b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an event listener for the plus icon in the trending stock entry
- [x] When the plus icon is clicked, get the information about that stock 
- [x] Get the information from the trendingTickers property of the data model 
- [x] Push the trendingStock information into the watchlist property of the data model
- [x] Create watchlist entries based on the current entries in the array
- [x] Switch the view to the watchlist container
- [x] Remove all unnecessary styling
- [x] Test all functionality 
- [x] Fix all errors
